# Generated by Django 3.2.4 on 2021-07-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210710_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(default='https://checkout.razorpay.com/v1/checkout.js'),
        ),
    ]
